## Importe

In [1]:
%load_ext autoreload
%autoreload 2


### Python Pakete

In [2]:

import locale
locale.setlocale(locale.LC_ALL, 'de_DE.UTF-8')
import datetime as dt

import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning) 

import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib as mpl

import numpy as np
import pandas as pd
from pandas import IndexSlice as IDX
pd.set_option("display.max_rows", 5)

### Datenbanken

In [3]:
import RomansThesis as RT
from RomansThesis import getData

Lade WetterDB...
Lade Raumklima...
Lade gespeicherte Datenbank...

# Anwesenheit

In [4]:
df = getData(value='Anwesenheit', app=['N', 'S']).resample('H').max()
df.to_csv('data/exporte/Anwesenheitssignal.csv')
df

bui                                LB                      MH              \
app                                 N           S           N           S
room                               WE          WE          WE          WE
value                     Anwesenheit Anwesenheit Anwesenheit Anwesenheit
Datetime
2021-02-08 11:00:00+01:00         NaN         NaN         NaN         NaN
2021-02-08 12:00:00+01:00         NaN         NaN         NaN         NaN
...                               ...         ...         ...         ...
2022-10-10 01:00:00+02:00         NaN         NaN         NaN         NaN
2022-10-10 02:00:00+02:00         NaN         NaN         NaN         NaN

bui                                MW
app                                 N           S
room                               WE          WE
value                     Anwesenheit Anwesenheit
Datetime
2021-02-08 11:00:00+01:00         NaN         NaN
2021-02-08 12:00:00+01:00         NaN         NaN
...                               ...         ...
2022-10-10 01:00:00+02:00         NaN         NaN
2022-10-10 02:00:00+02:00         NaN         NaN

[14607 rows x 6 columns]

# Heizung

In [5]:
df = getData(value='HK_IO', app=['N', 'S']).resample('H').max()
df.to_csv('data/exporte/Heizungssignal_hourly.csv')
df

bui                          LB                                  MH        \
app                           N                 S                 N
room                          B    SZ    WZ     B    SZ    WZ     B    SZ
value                     HK_IO HK_IO HK_IO HK_IO HK_IO HK_IO HK_IO HK_IO
Datetime
2021-02-08 11:00:00+01:00   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
2021-02-08 12:00:00+01:00   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
...                         ...   ...   ...   ...   ...   ...   ...   ...
2022-10-10 01:00:00+02:00   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
2022-10-10 02:00:00+02:00   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN

bui                                                  MW                    \
app                                 S                 N                 S
room                         WZ     B    SZ    WZ     B    SZ    WZ     B
value                     HK_IO HK_IO HK_IO HK_IO HK_IO HK_IO HK_IO HK_IO
Datetime
2021-02-08 11:00:00+01:00   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
2021-02-08 12:00:00+01:00   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
...                         ...   ...   ...   ...   ...   ...   ...   ...
2022-10-10 01:00:00+02:00   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
2022-10-10 02:00:00+02:00   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN

bui
app
room                         SZ    WZ
value                     HK_IO HK_IO
Datetime
2021-02-08 11:00:00+01:00   NaN   NaN
2021-02-08 12:00:00+01:00   NaN   NaN
...                         ...   ...
2022-10-10 01:00:00+02:00   NaN   NaN
2022-10-10 02:00:00+02:00   NaN   NaN

[14607 rows x 18 columns]